/**
  * TestConsole1Lib
  *
  * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io )
  */

;(function (angular) {
'use strict';

angular.module('TestConsole1Lib')
    .factory('APIController', ['$q', 'Configuration', 'HttpClient', 'APIHelper', 'BaseController', APIController
    ]);

    function APIController($q, Configuration, HttpClient, APIHelper, BaseController) {
        return {
            /**
             * @todo Add general description for this endpoint
             *
             * @param {array} model TODO: type description here
             * @param {bool} mboolean TODO: type description here
             *
             * @return {promise<Void>}
             */
            createDafa322Endpoint: function (model, mboolean) {

                //Create promise to return
                var _deffered = $q.defer();
                
                //prepare query string for API call
                var _baseUri = Configuration.BASEURI;
                var _queryBuilder = _baseUri + '/322/google';
                
                //validate and preprocess url
                var _queryUrl = APIHelper.cleanUrl(_queryBuilder);
                
                // prepare form data
                var _form = {
                    'model': model,
                    'Boolean': mboolean
                };

                // Remove null values
                APIHelper.cleanObject(_form);

                // prepare and invoke the API call request to fetch the response
                var _config = {
                    method: 'POST',
                    queryUrl: _queryUrl,
                    form: _form,
                };
                
                var _response = new HttpClient(_config);
                
                //process response
                _response.then(function success(_result) {
                    _deffered.resolve(_result);
                }, function error(_result){
                    // Error handling for custom HTTP status codes
                    _deffered.reject(APIHelper.appendContext({
                        errorMessage:'HTTP Response Not OK',
                        errorCode: _result.code,
                        errorResponse: _result.message
                    }, _result.getContext()));
                });
                
                return _deffered.promise;
            }
        };
    }

}(angular));
